name: Sync PX4 S3

permissions:
  contents: write

on:
  schedule:
    - cron: '0 11 * * 1' # Every Monday at 8AM GMT-3 (When I start working) 
  workflow_dispatch:

jobs:
  sync-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS command line
      run: |
        if ! command -v aws &> /dev/null; then
          apt update && apt install curl unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          rm -rf aws awscliv2.zip
        fi
        aws --version

    - name: Sync S3 bucket
      id: fetch
      run: |
        AWS_EC2_METADATA_DISABLED=true aws s3 sync s3://px4-travis/Firmware/master/_general master --exclude "params.*" --no-sign-request
        echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update files from ${{steps.fetch.outputs.date}}"

    - name: Keep Action Alive
      run: echo "Keep Action Alive"

  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: sync-s3
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
